const { injectManifest } = require('workbox-build');

// We reuse the configuration from the file generated by Workbox CLI
let workboxConfig = require('../workbox-config.js');

injectManifest(workboxConfig).then(({ count, size }) => {
  console.log(
    `Generated ${
      workboxConfig.swDest
    }, which will precache ${count} files, totaling ${size} bytes.`
  );
});